### ISSUE TITLE
Add option to "bypassCache"

### ISSUE THREAD

**Issue by Juraj-Masiar** [ericchase/addon--reload-all-tabs-in-window#3]
For me often happens that cached version is re-loaded even though there is a new version available.

Could you add option to Options page to use `bypassCache`?
API info:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/reload

Thank you!

**Comment by ericchase** [comment]
Hi!

As a note for those who don't know: This is how browsers normally work. Refreshing a page manually should also almost always re-load from the cache.

That said, how would you propose we add this feature?

**Comment by Juraj-Masiar** [comment]
Usually addons have an options page with some optional configuration (checkboxes, inputs, etc...).
I can see you have a an Options page but without any options yet :)

In this case it could be very simple - above your "Changelog" add a new section called "Options" where you put something like:
```
<label style="display: flex; align-items: center;"><input type="checkbox" id="bypassCache"> Bypass cache</label>
```
And then in your JS file find the checkbox by id and assign there event listener for change, something like:
```
document.getElementById('bypassCache').addEventListener('input', e => browser.storage.local.set({options: {bypassCache: e.target.checked}}));
```
Then in your code where you call tabs.reload you first load the configuration and set parameter accordingly.

I didn't tried the code so there could be issues, but overall it should work fine for this simple case :)

**Comment by ericchase** [comment]
Fairly straightforward. But that's a rather limiting mechanic for the user. It would be quite to pain to have to go through the options page each time you want to change it. Considering that using the cache is the normal action, forcing a cache-miss would be considered an exception. I would suggest using a modifier key when clicking the icon, as that is a more familiar route.

**Comment by Juraj-Masiar** [comment]
Well, I'm using your addon to reload only one specific set of pages where I always want to get the fresh version (once a week).
So I would be really happy if it could be set once and then used forever without thinking about pressing a key.
But having with a modifier key is also a good idea!
However I would suggest to do both though :)

**Comment by ericchase** [comment]
A good point. It is probably best to add both ways. I'll see what I can do.

**Comment by ericchase** [comment]
New version uploaded. Let me know if I broke something.

**Comment by ericchase** [comment]
Notes

From what I can tell, it seems like the cache is still checked for certain things. Might be an issue with how pages load other pages. Whatever it is, it seems to be outside the scope of what the extension can do.

**Comment by Juraj-Masiar** [comment]
I've tested it now and it seems to work, at least from what I can see in the Network tab in developer tools. But I will know for sure next Monday :)
**Thank you for implementing this so quick and making my life easier!**

Regarding your code - I would recommend you to checkout "async" and "await", it makes work with Promises much easier. For example:
```javascript
browser.storage.local.get()
  .then(data => console.log(data));
// can be written as:
const data = await browser.storage.local.get();
console.log(data);
```
More info: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await

**Comment by ericchase** [comment]
No problem and thanks for the tip. I prefer promises though. They offer much more power. The new code looks bad because I tailored it for simplicity when I first wrote this, and I didn't feel like rewriting much of it this time.
