### ISSUE TITLE
Add Icons for Dark Mode

### ISSUE THREAD

**Issue by ericchase** [ericchase/addon--reload-all-tabs-in-window#4]
Utilize the browserAction.setIcon() api to allow users to choose between light and dark mode icons, possibly more.
If auto-detection of theme colors is possible, maybe include that as well.

**Comment by ericchase** [comment]
If there is a way to dynamically load icons, perhaps through options menu, then that might be the route to pursue.

This way, users can upload their own icon to match their themes.

**Comment by allanlaal** [comment]
since this is a reload all tabs in *window* plugin, then the icon could be a retro blue border Window icon with a refresh in the middle

**Comment by ericchase** [comment]
True. I'd appreciate any homemade icons. But I probably won't update these extensions anymore. For any further updates, I would want to upload a new extension to the stores. That said, idk when or if I'll get around to it, because these are good enough for me.

**Comment by ericchase** [comment]
making 16x16 icons for chrome and firefox is difficult. firefox allows multiple sets of icons for dealing with dark/light theme, but (afaik) chrome does not. i came up with a fun icon that should be visible and somewhat recognizable. the color palette works for chrome, and i added 2 more sets that are more visible for dark and light themes on firefox. this should be good enough for now.

these changes are for the new Manifest V3 version of the extension. the MV2 extension will not change.
