### ISSUE TITLE
ADD tab/tabbar right click context menu option

### ISSUE THREAD

**Issue by allanlaal** [ericchase/addon--reload-all-tabs-in-window#5]
space is at a premium, so I tend to unpin most of my addon icons that offer a simple action

**Comment by ericchase** [comment]
I'm still upset, but since this is such an easy addition, here you go.

Is this what you wanted?

![image](https://github.com/user-attachments/assets/2590faa1-0053-4664-8d01-56d83d4eeb36)

**Comment by ericchase** [comment]
added in version 0.0.3 along with option to disable
