### ISSUE TITLE
FIX add user changeable random interval to delay between tabs reloading

### ISSUE THREAD

**Issue by allanlaal** [ericchase/addon--reload-all-tabs-in-window#7]
sadly almost useless without the ability  to set a (random from set range) interval to delay next tab load

**Comment by ericchase** [comment]
not sure what you mean. the extension works exactly as I want it to

**Comment by ericchase** [comment]
since you have 2 issues now, perhaps you might want to clone the repo and make the changes you like and upload your version to the web store

**Comment by allanlaal** [comment]
it reloads all the tabs at once, resulting in getting banned for ddosing

**Comment by ericchase** [comment]
sounds like a website issue/you have too many pages open? idk what to tell you

**Comment by ericchase** [comment]
well, actually, what i'd tell you is: feel free to clone the repo and add this feature, package the extension, open an account on the web store of whichever browser you use, upload your version of the extension and go ham! if you **really** want me to add this feature (well, i'm not very open to it after you gave me 1 star for a very specific use case, rather than the quality of the extension), then feel free to do a pull request and i'll see if i can get around to merging it (then building, packaging for chrome and firefox, updating all the descriptions and what not, and finally uploading the new version)

**Comment by allanlaal** [comment]
link my review and 'll delete it

**Comment by ericchase** [comment]
eh. maybe the low rating will keep my extension away from the search results. I wrote it for myself. the fact that others can make use of it is an extra. the only thing a low rating does is hurt other people who might have needed it. but it does what I want, so I'm good.

**Comment by ericchase** [comment]
The code for reloading can be found here:

service-worker.js
here
![image](https://github.com/user-attachments/assets/7715ef73-f969-4fc2-bfd1-95b6651bec23)
and here
![image](https://github.com/user-attachments/assets/738a1273-db8d-4129-9554-b3bfcf4d6c30)

As you'll notice, it's a very simple piece of code. Now, while your request to add a delay might _seem_ simple, there are actually a number of potential issues to consider:

What if the user clicks the extension icon multiple times? Generally, to add a _delay_ to the code, one could simply add `async` and `await` to the `reloadTab` function and call. But such a simple solution would then result in multiple _instances_ of reloading if the user clicks the icon multiple times. So now, the dev would need to devise a plan for handling this situation. It's possible that there are other situations that need to be considered.

I'd love to know what kind of solution you would come up with.

**Comment by ericchase** [comment]
Second scenario: Should the delay be applied to every tab indiscriminately, or should each domain have its own delay period? Of course, some users might want it to be per sub-domain, or per page. Where does it end?

**Comment by ericchase** [comment]
![image](https://github.com/user-attachments/assets/2d953416-df9d-45f5-ba06-fe6ead532a98)

**Comment by ericchase** [comment]
seems to work

**Comment by ericchase** [comment]
i added a Set for storing window.id so that subsequent requests to reload that window will fail until the first request finishes

**Comment by ericchase** [comment]
![image](https://github.com/user-attachments/assets/477228ea-4cf6-47a8-aab4-01df8f9b24d7)

there you go. don't say i never did nothin for you

**Comment by ericchase** [comment]
version 0.0.3 has been submitted
